name: packer 
on:
  push: 

env:
  PRODUCT_VERSION: "latest"
  VAULT_SKIP_VERIFY: "true"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with: 
          url: https://13.250.117.127:8200
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            aws/creds/vault-temp-role access_key | AWS_ACCESS_KEY_ID ;
            aws/creds/vault-temp-role secret_key | AWS_SECRET_ACCESS_KEY
      
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env. PRODUCT_VERSION }}
      
      - name: Run `packer init`
        id: init
        run: "packer init ."

      - name: Run `packer validate`
        id: validate
        run: "packer validate ."

      - name: Run `packer build`
        id: build
        run: "packer build ."